version: '3'

services:
  # Redis Cluster Nodes
  redis-node-1:
    image: redis:6.0-alpine
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.1

  redis-node-2:
    image: redis:6.0-alpine
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.2

  redis-node-3:
    image: redis:6.0-alpine
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.3

  redis-node-4:
    image: redis:6.0-alpine
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.4

  redis-node-5:
    image: redis:6.0-alpine
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.5

  redis-node-6:
    image: redis:6.0-alpine
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.6

  # Redis Cluster Setup
  redis-cluster-setup:
    image: redis:6.0-alpine
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      redis_cluster:
        ipv4_address: 172.32.1.7

  # Postgres Databases
  db_task_management:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  db_task_execution:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_execution_db
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped

  # Task Management Service
  task_management_service:
    build:
      context: ./task_management_service
      dockerfile: Dockerfile
    depends_on:
      - db_task_management
      - redis-cluster-setup
    environment:
      DATABASE_URL: postgresql://user:password@db_task_management:5432/task_management_db
      REDIS_CLUSTER_NODES: redis-node-1:7001,redis-node-2:7002,redis-node-3:7003
    networks:
      - backend
      - redis_cluster
    deploy:
      replicas: 3

  # Task Execution Service
  task_execution_service:
    build:
      context: ./task_execution_service
      dockerfile: Dockerfile
    depends_on:
      - db_task_execution
      - task_management_service
      - redis-cluster-setup
    environment:
      DATABASE_URL: postgresql://user:password@db_task_execution:5432/task_execution_db
      TASK_MANAGEMENT_URL: http://task_management_service:5000/tasks
      REDIS_CLUSTER_NODES: redis-node-1:7001,redis-node-2:7002,redis-node-3:7003
    networks:
      - backend
      - redis_cluster
    deploy:
      replicas: 3

  # Gateway Service
  gateway_pad:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    depends_on:
      - task_management_service
      - task_execution_service
    environment:
      TASK_MANAGEMENT_URL: http://task_management_service:5000/tasks
      TASK_EXECUTION_URL: http://task_execution_service:5001/
    networks:
      - backend
    restart: unless-stopped

  # Monitoring Services
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - backend

  # Nginx Service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway_pad
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  redis_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
