services:
  redis-node-1:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-1.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
    networks:
      - backend
    hostname: redis-node-1

  redis-node-2:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-2.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
    networks:
      - backend
    hostname: redis-node-2

  redis-node-3:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-3.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
    networks:
      - backend
    hostname: redis-node-3

  redis-node-4:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-4.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
    networks:
      - backend
    hostname: redis-node-4

  redis-node-5:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-5.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
    networks:
      - backend
    hostname: redis-node-5

  redis-node-6:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-conf/redis-node-6.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7006:7006"
    networks:
      - backend
    hostname: redis-node-6

  redis-cluster-setup:
    image: redis:latest
    ports:
      - "6999:6999"
    networks:
      - backend
    command: redis-cli -p 7000 --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 redis-node-4:7004 redis-node-5:7005 redis-node-6:7006 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - backend
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis-cluster-setup

  db_task_management:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  db_task_execution:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_execution_db
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped

  task_management_service:
    build:
      context: ./task_management_service
      dockerfile: Dockerfile
    depends_on:
      - db_task_management
      - redis-cluster-setup
    environment:
      DATABASE_URL: postgresql://user:password@db_task_management:5432/task_management_db
      REDIS_CLUSTER_NODES: redis-node-1:7001,redis-node-2:7002,redis-node-3:7003
    networks:
      - backend
      - redis_cluster
    deploy:
      replicas: 3
    ports:
      - "5000"

  task_execution_service:
    build:
      context: ./task_execution_service
      dockerfile: Dockerfile
    depends_on:
      - db_task_execution
      - task_management_service
      - redis-cluster-setup
    environment:
      DATABASE_URL: postgresql://user:password@db_task_execution:5432/task_execution_db
      TASK_MANAGEMENT_URL: http://task_management_service:5000/tasks
      REDIS_CLUSTER_NODES: redis-node-1:7001,redis-node-2:7002,redis-node-3:7003
    networks:
      - backend
      - redis_cluster
    deploy:
      replicas: 3
    ports:
      - "5001"

  gateway_pad:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    environment:
      TASK_MANAGEMENT_URL: http://task_management_service:5000/tasks
      TASK_EXECUTION_URL: http://task_execution_service:5001/
      TASK_EXECUTION_URLS: http://task_execution_service:5001/,http://task_execution_service:5001/,http://task_execution_service:5001/
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - gateway_pad
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  redis_cluster:
    driver: bridge
