global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task_management_service'
    static_configs:
      - targets: ['task_management_service:5000']

  - job_name: 'task_execution_service'
    static_configs:
      - targets: ['task_execution_service:5001']

  - job_name: 'gateway_pad'
    static_configs:
      - targets: ['gateway_pad:3000']
